Fix example code to match the documentation narrative
goldmansachs/reladomo-kata pull request #21
Opened 2017-03-25 05:20 UTC by epsstan

Set processing time in examples so that example behavior matches the narrative.
Make example code more consistent across bi-temporal chaining and audit-only chaining.

2017-03-25 21:09 UTC, gs-rezaem requested changes

2017-03-25 21:09 UTC, gs-rezaem commented on reladomo-tour/tour-examples/auditonly-bank/src/test/java/auditonlybank/api/AuditOnlyChainingInAction.java
> +        Without this, the processing time gets set to the time of running this program.
Add text:
Calling this method in production code violates the auditability of the data, which is the only reason the processingDate exists in the first place.

2017-03-25 21:09 UTC, gs-rezaem commented on reladomo-tour/tour-examples/auditonly-bank/src/test/java/auditonlybank/api/AuditOnlyChainingInAction.java
> +    private void setProcessingTime (String date, MithraTransaction tx)
Please rename this to appropriately named method, like "dontDoThisInProduction(date, tx)"

2017-03-28 03:32 UTC, epsstan commented
PR has been updated with the requested changes.

2017-03-28 14:26 UTC, merged